#ifndef __DMA_CONFIG_H__
#define __DMA_CONFIG_H__

#include <rtthread.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SPI1: DMA1 CH1/CH2 */
#if defined(BSP_SPI1_RX_USING_DMA) && !defined(SPI1_RX_DMA_INSTANCE)
#define SPI1_DMA_RX_IRQHandler DMA1_Channel1_IRQHandler
#define SPI1_RX_DMA_RCC RCC_AHB1ENR_DMA1EN
#define SPI1_RX_DMA_INSTANCE DMA1_Channel1
#define SPI1_RX_DMA_IRQ DMA1_Channel1_IRQn
#define SPI1_RX_DMA_REMAP DMA_CHANNEL_MAP_SPI1_RD
#endif

#if defined(BSP_SPI1_TX_USING_DMA) && !defined(SPI1_TX_DMA_INSTANCE)
#define SPI1_DMA_TX_IRQHandler DMA1_Channel2_IRQHandler
#define SPI1_TX_DMA_RCC RCC_AHB1ENR_DMA1EN
#define SPI1_TX_DMA_INSTANCE DMA1_Channel2
#define SPI1_TX_DMA_IRQ DMA1_Channel2_IRQn
#define SPI1_TX_DMA_REMAP DMA_CHANNEL_MAP_SPI1_WR
#endif

/* I2C2: DMA1 CH3/CH4 */
#if defined(BSP_I2C2_RX_USING_DMA) && !defined(I2C2_RX_DMA_INSTANCE)
#define I2C2_DMA_RX_IRQHandler DMA1_Channel3_IRQHandler
#define I2C2_RX_DMA_RCC RCC_AHB1ENR_DMA1EN
#define I2C2_RX_DMA_INSTANCE DMA1_Channel3
#define I2C2_RX_DMA_IRQ DMA1_Channel3_IRQn
#define I2C2_RX_DMA_REMAP DMA_CHANNEL_MAP_I2C2_RD
#endif

#if defined(BSP_I2C2_TX_USING_DMA) && !defined(I2C2_TX_DMA_INSTANCE)
#define I2C2_DMA_TX_IRQHandler DMA1_Channel4_IRQHandler
#define I2C2_TX_DMA_RCC RCC_AHB1ENR_DMA1EN
#define I2C2_TX_DMA_INSTANCE DMA1_Channel4
#define I2C2_TX_DMA_IRQ DMA1_Channel4_IRQn
#define I2C2_TX_DMA_REMAP DMA_CHANNEL_MAP_I2C2_WR
#endif

/* UART2: DMA1 CH5/CH6 */
#if defined(BSP_UART2_RX_USING_DMA) && !defined(UART2_RX_DMA_INSTANCE)
#define UART2_DMA_RX_IRQHandler DMA1_Channel5_IRQHandler
#define UART2_RX_DMA_RCC RCC_AHB1ENR_DMA1EN
#define UART2_RX_DMA_INSTANCE DMA1_Channel5
#define UART2_RX_DMA_IRQ DMA1_Channel5_IRQn
#define UART2_RX_DMA_REMAP DMA_CHANNEL_MAP_USART2_RD
#endif

#if defined(BSP_UART2_TX_USING_DMA) && !defined(UART2_TX_DMA_INSTANCE)
#define UART2_DMA_TX_IRQHandler DMA1_Channel6_IRQHandler
#define UART2_TX_DMA_RCC RCC_AHB1ENR_DMA1EN
#define UART2_TX_DMA_INSTANCE DMA1_Channel6
#define UART2_TX_DMA_IRQ DMA1_Channel6_IRQn
#define UART2_TX_DMA_REMAP DMA_CHANNEL_MAP_USART2_WR
#endif

/* SPI3: DMA2 CH1/CH2 */
#if defined(BSP_SPI3_TX_USING_DMA) && !defined(SPI3_TX_DMA_INSTANCE)
#define SPI3_DMA_TX_IRQHandler DMA2_Channel1_IRQHandler
#define SPI3_TX_DMA_RCC RCC_AHB1ENR_DMA2EN
#define SPI3_TX_DMA_INSTANCE DMA2_Channel1
#define SPI3_TX_DMA_IRQ DMA2_Channel1_IRQn
#define SPI3_TX_DMA_REMAP DMA_CHANNEL_MAP_SPI3_WR
#endif

#if defined(BSP_SPI3_RX_USING_DMA) && !defined(SPI3_RX_DMA_INSTANCE)
#define SPI3_DMA_RX_IRQHandler DMA2_Channel2_IRQHandler
#define SPI3_RX_DMA_RCC RCC_AHB1ENR_DMA2EN
#define SPI3_RX_DMA_INSTANCE DMA2_Channel2
#define SPI3_RX_DMA_IRQ DMA2_Channel2_IRQn
#define SPI3_RX_DMA_REMAP DMA_CHANNEL_MAP_SPI3_RD
#endif

#ifdef __cplusplus
}
#endif

#endif /* __DMA_CONFIG_H__ */
